spring:
  application:
    name: springboot-hi-redis
  codec:
    max-in-memory-size: -1
  profiles:
    active: dev
    include:
      - stream
---
spring:
  config:
    activate:
      on-profile: dev
  cloud.stream:
    binders:
      batchKafka:
        type: kafka
        environment:
          spring.cloud.stream:
            kafka:
              binder:
                brokers: localhost:9092
                zkNodes: localhost:2181
                autoCreateTopics: true

